// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int32              `json:"user_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	TokenHash string             `json:"token_hash"`
	IsRevoked bool               `json:"is_revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// user device information if available
	UserAgent pgtype.Text `json:"user_agent"`
	// user ip address if available
	UserIp pgtype.Text `json:"user_ip"`
}

type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
